version: '3'

services:

  # Jenkins server
  jenkins:
    #this one as not docker and docker-compose
    #image: jenkins/jenkins:lts
    #this one as no ansible  
    #image: trion/jenkins-docker-client
    #this one is outdated
    #image: h1kkan/jenkins-docker:lts
    image: lsioctl/jenkins-docker-ansible
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
      # to be able to launch siblings containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - front
    restart: "no"

  # Nginx for Blue/Green Deployments
  nginx:
    image: lsioctl/nginx
    ports:
      - "8081:80"
    networks:
      - front
    restart: "no"
 
volumes:
  jenkins:
  prod-data:

networks:
  front:
