version: '3'

services:

#  # Git 'server' 
#  git-server:
#    image: jkarlos/git-server-docker 
#    ports:
#      - "2222:22"
#    volumes:
#      - /root/cicdinfra/git-server/repos:/git-server/repos
#      - /root/cicdinfra/git-server/keys:/git-server/keys
#    restart: "no"

  # Jenkins server
  jenkins:
    #this one as not docker and docker-compose
    #image: jenkins/jenkins:lts
    #this one as no ansible  
    #image: trion/jenkins-docker-client
    #this one is outdated
    #image: h1kkan/jenkins-docker:lts
    image: lsioctl/jenkins-docker-ansible
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
      # to be able to launch siblings containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"

  # Prod server
  prod:
    #this one as not docker and docker-compose
    #image: jenkins/jenkins:lts
    image: tiangolo/uwsgi-nginx-flask:python3.7
    ports:
      - "8081:80"
    volumes:
      - prod-data:/var/data
    restart: "no"
 
volumes:
  jenkins:
  prod-data:
